name: aarch64 CI
on:
  pull_request:
    branches:
      - '**'
      - '!mainline'

jobs:
  kernel-build-job:
    runs-on:
      labels: kernel-build-arm64
    container:
      image: rockylinux:9
      env:
        ROCKY_ENV: rocky9
      ports:
        - 80
      options: --cpus 8
    steps:
      - name: Install tools and Libraries
        run: |
          dnf groupinstall 'Development Tools' -y
          dnf install --enablerepo=crb bc dwarves kernel-devel openssl-devel elfutils-libelf-devel -y
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: Build the Kernel
        run: |
          git config --global --add safe.directory /__w/kernel-src-tree/kernel-src-tree
          cp configs/kernel-aarch64-rhel.config .config
          make ARCH=arm64 CROSS_COMPILE=./scripts/dummy-tools/ olddefconfig
          make -j8
      - name: Check kabi
        run: |
          git clone --branch r9 --single-branch https://git.rockylinux.org/staging/rpms/kernel.git kernel-dist-git
          git -C kernel-dist-git reset --hard imports/r9/kernel-5.14.0-284.30.1.el9_2
          ./kernel-dist-git/SOURCES/check-kabi -k ./kernel-dist-git/SOURCES/Module.kabi_aarch64 -s Module.symvers
