name: x86_64 CI
on:
  pull_request:
    branches:
      - '**'
      - '!mainline'

jobs:
  kernel-build-job:
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
          path: kernel-src-tree

      - name: Install rinse
        run: |
          sudo apt-get install rinse

      - name: Build centos7 chroot
        run: |
          sudo rinse --distribution centos-7 \
                --mirror http://dl.rockylinux.org/vault/centos/7/os/x86_64/Packages \
                --arch amd64 \
                --directory centos-7-chroot

      - name: Point yum to vault (in chroot)
        run: |
          sudo sed -e '/mirrorlist=.*/d' \
              -e 's/#baseurl=/baseurl=/' \
              -e "s/\$releasever/7.9.2009/g" \
              -e "s/mirror.centos.org/dl.rockylinux.org\/vault/g" \
              -i centos-7-chroot/etc/yum.repos.d/CentOS-Base.repo

      - name: Install tools and Libraries (in chroot)
        run: |
          sudo chroot centos-7-chroot yum groupinstall 'Development Tools' -y
          sudo chroot centos-7-chroot yum install bc dwarves git glibc-devel hostname kernel-devel mpfr openssl openssl-devel elfutils-libelf-devel wget -y

      - name: Build the Kernel (in chroot)
        run: |
          sudo mv kernel-src-tree centos-7-chroot
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && cp configs/kernel-3.10.0-x86_64.config .config"
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && make olddefconfig"
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && make -j$(nproc)"
      - name: Check kabi
        run: |
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && wget https://dl.rockylinux.org/vault/centos/7.9.2009/updates/x86_64/Packages/kernel-3.10.0-1160.119.1.el7.src.rpm"
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && rpm2cpio kernel-3.10.0-1160.119.1.el7.src.rpm | cpio -ivd check-kabi Module.kabi_x86_64"
          sudo chroot centos-7-chroot sh -c "cd kernel-src-tree && ./check-kabi -k ./Module.kabi_x86_64 -s Module.symvers"
