name: kseltest Builder
on:
  push:
    branches:
      - 'ciqlts9_4'

jobs:
  kselftest-build-job:
    runs-on:
      labels: ubuntu-latest
    container:
      image: rockylinux:9
      env:
        ROCKY_ENV: rocky9
      ports:
        - 80
    steps:
      - name: Install tools and Libraries
        run: |
          dnf groupinstall 'Development Tools' -y
          dnf install --enablerepo=crb bc dwarves kernel-devel openssl-devel elfutils-libelf-devel -y
          dnf install alsa-lib-devel clang libcap-devel libcap-ng-devel libubsan numactl-devel rsync -y
          dnf install 'dnf-command(config-manager)' -y
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install gh -y
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: Build kselftest tarball
        run: |
          git config --global --add safe.directory /__w/kernel-src-tree/kernel-src-tree
          cp configs/kernel-x86_64-rhel.config .config
          make ARCH=x86_64 CROSS_COMPILE=./scripts/dummy-tools/ olddefconfig
          make -C tools/testing/selftests gen_tar
      - name: Create Release and Upload Kselftest Tarball
        run: |
          gh release create kselftest-${{ github.ref_name }} tools/testing/selftests/kselftest_install/kselftest-packages/kselftest.tar.gz --notes "Kselftest build from commit ${{ github.sha }}" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
