name: Kernel Sync

on:
  #schedule:
  #  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         include:
           - branch: kernel-mainline
             remote: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
             remote_branch: master
           - branch: stable_6.12.y
             remote: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
             remote_branch: linux-6.12.y
           - branch: centos9
             remote: https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9
             remote_branch: main

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: ${{ matrix.branch }}
      REMOTE: ${{ matrix.remote }}
      REMOTE_BRANCH: ${{ matrix.remote_branch }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Sync kernel source
        run: |
          set -e
          
          #git clone "https://oauth2:$GITHUB_TOKEN@github.com/ctrliq/kernel-src-tree" kernel
          git clone "https://oauth2:$GITHUB_TOKEN@github.com/bmastbergen/kernel-src-tree" kernel
          git -C kernel config user.name "github-actions[bot]"
          git -C kernel config user.email "github-actions[bot]@users.noreply.github.com"

          git -C kernel remote add upstream ${REMOTE}
          git -C kernel fetch upstream --tags
          git -C kernel push origin "refs/remotes/upstream/${REMOTE_BRANCH}:refs/heads/${BRANCH}"

