name: Validate Kernel Commits

on:
  workflow_call:
    # No inputs needed - uses github context from caller

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-kernel-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Checkout kernel-src-tree-tools
        uses: actions/checkout@v4
        with:
          repository: ctrliq/kernel-src-tree-tools
          ref: 'mainline'
          path: kernel-src-tree-tools

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run upstream fixes check
        id: check-kernel-commits
        working-directory: kernel-src-tree-tools
        run: |
          set +e  # Don't exit on error, we want to capture the output
          python3 check_kernel_commits.py --repo .. --pr_branch "${{ github.head_ref }}" --base_branch "${{ github.base_ref }}" --markdown --check-cves | tee ../result.txt
          EXIT_CODE=$?

          # Check if the script failed
          if [ $EXIT_CODE -ne 0 ]; then
            echo "❌ Kernel commits check failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi

          # Check for findings - run grep first, capture result
          grep -q -v "All referenced commits exist upstream and have no Fixes: tags." ../result.txt
          GREP_EXIT=$?
          set -e  # Re-enable exit on error

          # grep returns 0 if match found, 1 if no match, 2 on error
          if [ $GREP_EXIT -eq 2 ]; then
            echo "❌ Error reading check results"
            exit $GREP_EXIT
          elif [ $GREP_EXIT -eq 0 ]; then
            echo "has_findings=true" >> $GITHUB_OUTPUT
          else
            echo "has_findings=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if issues found
        if: steps.check-kernel-commits.outputs.has_findings == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! gh pr comment ${{ github.event.pull_request.number }} \
            --body-file result.txt \
            --repo ${{ github.repository }}; then
            echo "❌ Failed to post check-kernel-commits comment to PR"
            exit 1
          fi

      - name: Install build dependencies for patchutils
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool gnulib

      - name: Clone and build custom patchutils
        run: |
          git clone https://github.com/kerneltoast/patchutils.git --depth=1 --revision=32e5f1df96920f1d24beb910346f01acab8b0bd8
          cd patchutils
          ./bootstrap
          ./configure
          make -j$(nproc)

      - name: Run interdiff check
        id: interdiff
        working-directory: kernel-src-tree-tools
        run: |
          set +e  # Don't exit on error, we want to capture the output
          python3 run_interdiff.py --repo .. --pr_branch "${{ github.head_ref }}" --base_branch "${{ github.base_ref }}" --markdown --interdiff ../patchutils/src/interdiff | tee ../interdiff_result.txt
          EXIT_CODE=$?

          # Check if the script failed
          if [ $EXIT_CODE -ne 0 ]; then
            echo "❌ Interdiff check failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi

          # Check for differences - run grep first, capture result
          grep -q -v "All backported commits match their upstream counterparts." ../interdiff_result.txt
          GREP_EXIT=$?
          set -e  # Re-enable exit on error

          # grep returns 0 if match found, 1 if no match, 2 on error
          if [ $GREP_EXIT -eq 2 ]; then
            echo "❌ Error reading interdiff results"
            exit $GREP_EXIT
          elif [ $GREP_EXIT -eq 0 ]; then
            echo "has_differences=true" >> $GITHUB_OUTPUT
          else
            echo "has_differences=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if interdiff differences found
        if: steps.interdiff.outputs.has_differences == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! gh pr comment ${{ github.event.pull_request.number }} \
            --body-file interdiff_result.txt \
            --repo ${{ github.repository }}; then
            echo "❌ Failed to post interdiff comment to PR"
            exit 1
          fi

