name: VM Test
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  vm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install tools
        run: |
          sudo apt-get install bison build-essential cowsay flex libelf-dev libncurses-dev libssl-dev virtme-ng

      - name: Run vng
        run: |
          sed -i 's/set_page_dirty = v9fs_set_page_dirty/dirty_folio = v9fs_dirty_folio/g' fs/9p/vfs_addr.c
          sed -i 's/v9fs_set_page_dirty __set_page_dirty_nobuffers/v9fs_dirty_folio filemap_dirty_folio/g' fs/9p/vfs_addr.c
          sudo vng --config configs/kernel-x86_64-rhel.config
          sudo vng --cpus $(nproc) -- uname -r | cowsay
